spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fornecedor?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: cami
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
